// Banco de dados dos produtos

const data = [{
    id: 1,
    img: "../img/sem título (técnica mista).jpg",
    nameItem: "Sem título, 2020",
    description: "Técnica mista, 28 x 29,5 cm.",
    value: 42,
    addCart: "Adicionar ao carrinho",
    tag: ["2020"],
  },
  {
    id: 2,
    img: "../img/eu pertenço ao hoje.jpg",
    nameItem: "Eu pertenço ao hoje, 2018",
    description: "Técnica mista, 21 x 29,7 cm",
    value: 20,
    addCart: "Adicionar ao carrinho",
    tag: ["2018"],
  },
  {
    id: 3,
    img: "../img/gravura 1.jpg",
    nameItem: "Xilogravura, 2019",
    description: "20,5 x 27, 7 cm",
    value: 60,
    addCart: "Adicionar ao carrinho",
    tag: ["2019"],
  },
  {
    id: 4,
    img: "../img/imersão.jpg",
    nameItem: "Imersão, 2019",
    description: " Técnica mista, 21 x 29,7 cm.",
    value: 20,
    addCart: "Adicionar ao carrinho",
    tag: ["2019"],
  },
  {
    id: 5,
    img: "../img/mulheres são sementes.jpg",
    nameItem: "Mulheres são sementes, 2018",
    description: "Lápis aquarelável sobre papel canson, 21 x 29,7 cm.",
    value: 25,
    addCart: "Adicionar ao carrinho",
    tag: ["2018"],
  },
  {
    id: 6,
    img: "../img/O mistério da flor.jpg",
    nameItem: "O mistério da flor, 2019",
    description: "Técnica mista, 29,7 x 42 cm.",
    value: 45,
    addCart: "Adicionar ao carrinho",
    tag: ["2019"],
  },
]